/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagingRouteImport } from './routes/paging'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProtectedRouteImport } from './routes/_auth/protected'

const PagingRoute = PagingRouteImport.update({
  id: '/paging',
  path: '/paging',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProtectedRoute = AuthProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/paging': typeof PagingRoute
  '/protected': typeof AuthProtectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/paging': typeof PagingRoute
  '/protected': typeof AuthProtectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/paging': typeof PagingRoute
  '/_auth/protected': typeof AuthProtectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customScript.js' | '/login' | '/paging' | '/protected'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customScript.js' | '/login' | '/paging' | '/protected'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/customScript.js'
    | '/login'
    | '/paging'
    | '/_auth/protected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  LoginRoute: typeof LoginRoute
  PagingRoute: typeof PagingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paging': {
      id: '/paging'
      path: '/paging'
      fullPath: '/paging'
      preLoaderRoute: typeof PagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/protected': {
      id: '/_auth/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof AuthProtectedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthProtectedRoute: typeof AuthProtectedRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProtectedRoute: AuthProtectedRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  LoginRoute: LoginRoute,
  PagingRoute: PagingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
