/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as UserIdMoviesRouteImport } from './routes/$userId.movies'
import { Route as UserIdBooksRouteImport } from './routes/$userId.books'
import { Route as AuthMoviesNewRouteImport } from './routes/_auth/movies.new'
import { Route as AuthMoviesMovieIdRouteImport } from './routes/_auth/movies.$movieId'
import { Route as AuthBooksNewRouteImport } from './routes/_auth/books.new'
import { Route as AuthBooksBookIdRouteImport } from './routes/_auth/books.$bookId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const UserIdMoviesRoute = UserIdMoviesRouteImport.update({
  id: '/$userId/movies',
  path: '/$userId/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdBooksRoute = UserIdBooksRouteImport.update({
  id: '/$userId/books',
  path: '/$userId/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMoviesNewRoute = AuthMoviesNewRouteImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMoviesMovieIdRoute = AuthMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBooksNewRoute = AuthBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBooksBookIdRoute = AuthBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/$userId/books': typeof UserIdBooksRoute
  '/$userId/movies': typeof UserIdMoviesRoute
  '/profile': typeof AuthProfileRoute
  '/books/$bookId': typeof AuthBooksBookIdRoute
  '/books/new': typeof AuthBooksNewRoute
  '/movies/$movieId': typeof AuthMoviesMovieIdRoute
  '/movies/new': typeof AuthMoviesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/$userId/books': typeof UserIdBooksRoute
  '/$userId/movies': typeof UserIdMoviesRoute
  '/profile': typeof AuthProfileRoute
  '/books/$bookId': typeof AuthBooksBookIdRoute
  '/books/new': typeof AuthBooksNewRoute
  '/movies/$movieId': typeof AuthMoviesMovieIdRoute
  '/movies/new': typeof AuthMoviesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/$userId/books': typeof UserIdBooksRoute
  '/$userId/movies': typeof UserIdMoviesRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/books/$bookId': typeof AuthBooksBookIdRoute
  '/_auth/books/new': typeof AuthBooksNewRoute
  '/_auth/movies/$movieId': typeof AuthMoviesMovieIdRoute
  '/_auth/movies/new': typeof AuthMoviesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/register'
    | '/$userId/books'
    | '/$userId/movies'
    | '/profile'
    | '/books/$bookId'
    | '/books/new'
    | '/movies/$movieId'
    | '/movies/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/register'
    | '/$userId/books'
    | '/$userId/movies'
    | '/profile'
    | '/books/$bookId'
    | '/books/new'
    | '/movies/$movieId'
    | '/movies/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/register'
    | '/$userId/books'
    | '/$userId/movies'
    | '/_auth/profile'
    | '/_auth/books/$bookId'
    | '/_auth/books/new'
    | '/_auth/movies/$movieId'
    | '/_auth/movies/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
  RegisterRoute: typeof RegisterRoute
  UserIdBooksRoute: typeof UserIdBooksRoute
  UserIdMoviesRoute: typeof UserIdMoviesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$userId/movies': {
      id: '/$userId/movies'
      path: '/$userId/movies'
      fullPath: '/$userId/movies'
      preLoaderRoute: typeof UserIdMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/books': {
      id: '/$userId/books'
      path: '/$userId/books'
      fullPath: '/$userId/books'
      preLoaderRoute: typeof UserIdBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/movies/new': {
      id: '/_auth/movies/new'
      path: '/movies/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof AuthMoviesNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/movies/$movieId': {
      id: '/_auth/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof AuthMoviesMovieIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/books/new': {
      id: '/_auth/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthBooksNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/books/$bookId': {
      id: '/_auth/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthBooksBookIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthBooksBookIdRoute: typeof AuthBooksBookIdRoute
  AuthBooksNewRoute: typeof AuthBooksNewRoute
  AuthMoviesMovieIdRoute: typeof AuthMoviesMovieIdRoute
  AuthMoviesNewRoute: typeof AuthMoviesNewRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthBooksBookIdRoute: AuthBooksBookIdRoute,
  AuthBooksNewRoute: AuthBooksNewRoute,
  AuthMoviesMovieIdRoute: AuthMoviesMovieIdRoute,
  AuthMoviesNewRoute: AuthMoviesNewRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
  RegisterRoute: RegisterRoute,
  UserIdBooksRoute: UserIdBooksRoute,
  UserIdMoviesRoute: UserIdMoviesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
