/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthMoviesRouteImport } from './routes/_auth/movies'
import { Route as AuthBooksRouteImport } from './routes/_auth/books'

const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMoviesRoute = AuthMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBooksRoute = AuthBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/books': typeof AuthBooksRoute
  '/movies': typeof AuthMoviesRoute
  '/profile': typeof AuthProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/books': typeof AuthBooksRoute
  '/movies': typeof AuthMoviesRoute
  '/profile': typeof AuthProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/_auth/books': typeof AuthBooksRoute
  '/_auth/movies': typeof AuthMoviesRoute
  '/_auth/profile': typeof AuthProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/books'
    | '/movies'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/books'
    | '/movies'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/customScript.js'
    | '/login'
    | '/people'
    | '/_auth/books'
    | '/_auth/movies'
    | '/_auth/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/movies': {
      id: '/_auth/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AuthMoviesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/books': {
      id: '/_auth/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthBooksRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthBooksRoute: typeof AuthBooksRoute
  AuthMoviesRoute: typeof AuthMoviesRoute
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthBooksRoute: AuthBooksRoute,
  AuthMoviesRoute: AuthMoviesRoute,
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
